import { useEffect, useMemo, useState } from 'react'
import { CalendarPlus, Check, CircleHelp, Clock3, MessageCircleMore, Trash2 } from 'lucide-react'
import { bridge } from '../lib/bridge'

const BOND_SYSTEMS = ['household_intimate', 'kin_family', 'chosen_family', 'friendship', 'role_community', 'acquaintance_contextual']
const CLOSENESS = ['essential', 'inner', 'active', 'wider_world', 'historical_dormant', 'intentionally_distant']
const TRAJECTORIES = ['new', 'deepening', 'steady', 'cyclical', 'quiet_but_intact', 'changing_form', 'drifting', 'strained', 'repairing', 'dormant_meaningful', 'resting', 'concluded', 'ambiguous', 'unknown']
const INTENTIONS = ['understand', 'preserve', 'deepen', 'revive', 'repair', 'reframe', 'boundary', 'rest', 'conclude']
const FORMS = ['dyadic', 'group_carried', 'mixed', 'activity_led', 'disclosure_led', 'practical_support_led', 'long_distance', 'seasonal_ritual', 'role_bound', 'mentor', 'caregiving', 'bridge', 'household_interdependent', 'unclear']
const WORLDS = ['childhood', 'school', 'university', 'professional', 'sports', 'parenting', 'neighbourhood', 'faith_community', 'migration_diaspora', 'online', 'creative', 'volunteering', 'health_caregiving', 'personal', 'family']
const ROLES = ['friend', 'close_friend', 'best_friend', 'chosen_family', 'parent', 'child', 'sibling', 'extended_family', 'romantic_partner', 'spouse', 'co_parent', 'household_partner', 'former_partner', 'mentor', 'mentee', 'colleague', 'former_colleague', 'professional_collaborator', 'community_peer', 'teammate', 'neighbour', 'caregiver', 'care_recipient']
const ROMANTIC_STAGES = ['exploring', 'early_dating', 'established_dating', 'long_distance', 'cohabiting', 'engaged', 'married_or_long_term', 'parenting_partnership', 'living_apart_together', 'separating', 'former_partner', 'co_parent', 'concluded_or_no_contact']
const CADENCES = [['', 'No recurring rhythm'], ['7', 'About weekly'], ['14', 'Every two weeks'], ['30', 'Monthly'], ['60', 'Every two months'], ['90', 'Quarterly'], ['180', 'Twice a year'], ['365', 'Yearly ritual']]
const INTERACTION_TYPES = ['phone_call', 'video_call', 'in_person', 'shared_activity', 'caregiving', 'letter_or_card', 'other']
const EXPERIENCE_DIMENSIONS = ['felt_closeness', 'satisfaction', 'companionship_joy', 'mutual_knowing', 'responsiveness', 'reliability_alliance', 'support_fit', 'practical_help', 'emotional_security', 'mutuality', 'conflict_ambivalence', 'repair_boundaries', 'identity_belonging']
const EXPRESSION_OPTIONS = ['verbal_affection', 'practical_help', 'checking_in', 'shared_activity', 'humour_teasing', 'physical_presence', 'family_inclusion', 'advice', 'gifts', 'comfortable_silence']

const friendly = (value) => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
const number = (value) => new Intl.NumberFormat().format(Number(value || 0))
const fullDate = (value) => value ? new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Not recorded'
const errorMessage = (error) => String(error?.message || error || 'Something went wrong.').replace(/^Error invoking remote method '[^']+': Error: /, '')
const localDateTimeValue = (date = new Date()) => {
  const offset = date.getTimezoneOffset() * 60_000
  return new Date(date.getTime() - offset).toISOString().slice(0, 16)
}

function ChoiceGrid({ options, value = [], onChange }) {
  return <div className="v4-choice-grid">{options.map((option) => <button type="button" key={option} className={value.includes(option) ? 'selected' : ''} onClick={() => onChange(value.includes(option) ? value.filter((item) => item !== option) : [...value, option])}>{value.includes(option) ? <Check /> : null}{friendly(option)}</button>)}</div>
}

export function RelationshipContextEditor({ form, setForm, busy, onSave, onCancel }) {
  const norms = form.norms || {}
  const setNorm = (key, value) => setForm({ ...form, norms: { ...norms, [key]: value } })
  const romantic = (form.roles || []).some((role) => ['romantic_partner', 'spouse', 'former_partner'].includes(role))
  return <div className="v4-relationship-form">
    <div className="v4-form-pair"><label><span>Relationship system</span><select value={form.primaryClass} onChange={(event) => setForm({ ...form, primaryClass: event.target.value })}>{BOND_SYSTEMS.map((item) => <option key={item} value={item}>{friendly(item)}</option>)}</select></label><label><span>Your own description</span><input value={form.specificRelationship || ''} onChange={(event) => setForm({ ...form, specificRelationship: event.target.value })} placeholder="Old school friend, cousin, mentor…" /></label></div>
    <section><strong>Roles that coexist here</strong><small>A person can be family, friend and collaborator at the same time.</small><ChoiceGrid options={ROLES} value={form.roles || []} onChange={(roles) => setForm({ ...form, roles, primaryRole: roles.includes(form.primaryRole) ? form.primaryRole : roles[0] || null })} /></section>
    {romantic ? <label><span>Romantic stage · declared by you</span><select value={form.relationshipStage || ''} onChange={(event) => setForm({ ...form, relationshipStage: event.target.value || null })}><option value="">Not specified</option>{ROMANTIC_STAGES.map((item) => <option key={item} value={item}>{friendly(item)}</option>)}</select><small>Nearness never infers romantic stage from message tone.</small></label> : null}
    <div className="v4-form-pair"><label><span>Felt closeness</span><select value={form.closeness} onChange={(event) => setForm({ ...form, closeness: event.target.value })}>{CLOSENESS.map((item) => <option key={item} value={item}>{friendly(item)}</option>)}</select></label><label><span>Current trajectory</span><select value={form.trajectory} onChange={(event) => setForm({ ...form, trajectory: event.target.value })}>{TRAJECTORIES.map((item) => <option key={item} value={item}>{friendly(item)}</option>)}</select></label></div>
    <div className="v4-form-pair"><label><span>Your intention</span><select value={form.intention || ''} onChange={(event) => setForm({ ...form, intention: event.target.value || null })}><option value="">No Care intention</option>{INTENTIONS.map((item) => <option key={item} value={item}>{friendly(item)}</option>)}</select></label><label><span>Rhythm that would feel right</span><select value={form.cadenceDays || ''} onChange={(event) => setForm({ ...form, cadenceDays: event.target.value })}>{form.cadenceDays && !CADENCES.some(([value]) => Number(value) === Number(form.cadenceDays)) ? <option value={form.cadenceDays}>Every {form.cadenceDays} days</option> : null}{CADENCES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    <section><strong>Social worlds</strong><ChoiceGrid options={WORLDS} value={form.socialWorlds} onChange={(socialWorlds) => setForm({ ...form, socialWorlds })} /></section>
    <section><strong>Relationship forms</strong><ChoiceGrid options={FORMS} value={form.forms} onChange={(forms) => setForm({ ...form, forms })} /></section>
    <section className="v4-norms"><div><strong>How communication works here</strong><small>These relationship-specific meanings outrank general assumptions.</small></div><label><span>What does silence tend to mean?</span><input value={norms.silenceMeaning || ''} onChange={(event) => setNorm('silenceMeaning', event.target.value)} placeholder="Comfortable continuity, distance, busyness, unknown…" /></label><label><span>How does practical care show up?</span><input value={norms.practicalCareSignificance || ''} onChange={(event) => setNorm('practicalCareSignificance', event.target.value)} placeholder="Advice, food, logistics, checking I arrived…" /></label><label><span>Humour and teasing</span><input value={norms.humourAndTeasingNorm || ''} onChange={(event) => setNorm('humourAndTeasingNorm', event.target.value)} placeholder="Running jokes, affectionate mockery, not important…" /></label><label><span>Hierarchy or role expectations</span><input value={norms.hierarchyOrRoleEffect || ''} onChange={(event) => setNorm('hierarchyOrRoleEffect', event.target.value)} placeholder="Elder/younger roles, mentoring, caregiving…" /></label><label><span>Language and code-switching</span><input value={norms.languageAndCodeSwitching || ''} onChange={(event) => setNorm('languageAndCodeSwitching', event.target.value)} placeholder="Hindi-English, family shorthand, different languages by context…" /></label><label><span>Recurring rituals</span><input value={norms.recurringRituals || ''} onChange={(event) => setNorm('recurringRituals', event.target.value)} placeholder="Sunday cricket, birthday call, festival visit…" /></label></section>
    <section><strong>How care is expressed</strong><ChoiceGrid options={EXPRESSION_OPTIONS} value={norms.careExpressedAs || []} onChange={(value) => setNorm('careExpressedAs', value)} /></section>
    <section><strong>How you want to receive care</strong><ChoiceGrid options={EXPRESSION_OPTIONS} value={norms.careWantedAs || []} onChange={(value) => setNorm('careWantedAs', value)} /><label><span>Expression Match, in your words</span><select value={norms.expressionMatchState || 'needs_context'} onChange={(event) => setNorm('expressionMatchState', event.target.value)}><option value="needs_context">Needs context</option><option value="well_matched">Well matched</option><option value="different_but_satisfying">Different but satisfying</option><option value="different_and_painful">Different and painful</option><option value="mixed">Mixed</option><option value="changing">Changing</option></select></label><label><span>What matters about that difference?</span><textarea value={norms.expressionMatchNote || ''} onChange={(event) => setNorm('expressionMatchNote', event.target.value)} /></label></section>
    <label><span>What the archive cannot know</span><textarea value={form.notes || ''} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Shared history, what silence means here, boundaries…" /></label>
    {['revive', 'repair'].includes(form.intention) ? <label className="v4-checkline"><input type="checkbox" checked={norms.reconnectionFeelsSafe === true} onChange={(event) => setNorm('reconnectionFeelsSafe', event.target.checked ? true : null)} /><span><strong>Reconnection feels safe to consider.</strong><small>If this is not confirmed, Care offers reflection rather than contact.</small></span></label> : null}
    <div className="v4-control-stack"><label className="v4-checkline"><input type="checkbox" checked={Boolean(form.intentionallyQuiet)} onChange={(event) => setForm({ ...form, intentionallyQuiet: event.target.checked })} /><span><strong>Do not suggest contact right now</strong><small>Boundary, rest and conclusion outrank reminders.</small></span></label><label className="v4-checkline"><input type="checkbox" checked={Boolean(form.analysisDisabled)} onChange={(event) => setForm({ ...form, analysisDisabled: event.target.checked })} /><span><strong>Do not analyse this relationship</strong><small>Imported history remains local and visible, but portrait analysis is blocked.</small></span></label><label className="v4-checkline"><input type="checkbox" checked={Boolean(form.careDisabled)} onChange={(event) => setForm({ ...form, careDisabled: event.target.checked })} /><span><strong>Disable Care for this relationship</strong><small>No suggestions will be generated.</small></span></label><label className="v4-checkline"><input type="checkbox" checked={Boolean(form.hiddenFromAtlas)} onChange={(event) => setForm({ ...form, hiddenFromAtlas: event.target.checked })} /><span><strong>Hide from the visual atlas</strong><small>The person remains searchable and nothing is deleted.</small></span></label></div>
    <div className="v4-sheet-actions"><button className="v4-primary" disabled={busy} onClick={onSave}>{busy ? 'Saving…' : <><Check />Save relationship</>}</button><button className="v4-outline" onClick={onCancel}>Cancel</button></div>
  </div>
}

export function CommunicationEcology({ person }) {
  const ecology = person.communicationEcology || {}
  const modalities = Object.entries(ecology.modalityCounts || {}).sort((a, b) => b[1] - a[1])
  return <section className="v4-ecology"><div className="v4-section-heading"><div><span>Visible communication ecology</span><h3>What the archive can—and cannot—see</h3></div><CircleHelp /></div><div className="v4-recency-ladder"><div><small>Last visible touch</small><strong>{fullDate(ecology.lastVisibleTouch)}</strong><p>Any attributable message or media event.</p></div><div><small>Last interaction episode</small><strong>{fullDate(ecology.lastInteractionEpisode)}</strong><p>A mutual or structurally substantive exchange.</p></div><div><small>Last meaningful contact</small><strong>{fullDate(ecology.lastMeaningfulContact)}</strong><p>Only an offline moment you confirmed as meaningful.</p></div></div><div className="v4-ecology-grid"><div><small>Direct</small><strong>{number(ecology.scopeCounts?.direct_dyadic)}</strong></div><div><small>Person in groups</small><strong>{number(ecology.scopeCounts?.person_in_group)}</strong></div><div><small>Interaction episodes</small><strong>{number(ecology.substantiveEpisodeCount)}</strong></div><div><small>Offline moments</small><strong>{number(ecology.manualInteractionCount)}</strong></div></div>{modalities.length ? <div className="v4-modality-list">{modalities.map(([name, count]) => <span key={name}><b>{friendly(name)}</b>{number(count)}</span>)}</div> : null}<p className="v4-caveat">{ecology.coverage?.caveat}</p></section>
}

export function ManualMoments({ person, onChanged }) {
  const [adding, setAdding] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [form, setForm] = useState({ occurredAt: localDateTimeValue(), interactionType: 'phone_call', meaningful: true, title: '', notes: '' })
  async function save() { setBusy(true); setError(''); try { await bridge.people.addManualInteraction(person.id, { ...form, occurredAt: new Date(form.occurredAt).toISOString() }); setAdding(false); await onChanged() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  async function remove(id) { setBusy(true); try { await bridge.people.deleteManualInteraction(person.id, id); await onChanged() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <section className="v4-manual"><div className="v4-section-heading"><div><span>Calls and real life</span><h3>Moments the archive missed</h3></div><button className="v4-outline" onClick={() => setAdding(!adding)}><CalendarPlus />Add</button></div>{error ? <p className="v4-inline-error">{error}</p> : null}{adding ? <div className="v4-inline-form"><div className="v4-form-pair"><label><span>When</span><input type="datetime-local" value={form.occurredAt} onChange={(event) => setForm({ ...form, occurredAt: event.target.value })} /></label><label><span>What happened</span><select value={form.interactionType} onChange={(event) => setForm({ ...form, interactionType: event.target.value })}>{INTERACTION_TYPES.map((item) => <option key={item} value={item}>{friendly(item)}</option>)}</select></label></div><label><span>A short label</span><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Long phone call, weekend together…" /></label><label><span>Anything worth remembering?</span><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><label className="v4-checkline"><input type="checkbox" checked={form.meaningful} onChange={(event) => setForm({ ...form, meaningful: event.target.checked })} /><span><strong>This was meaningful contact.</strong><small>Only you can make this confirmation.</small></span></label><div><button className="v4-primary" disabled={busy} onClick={save}>Save moment</button><button className="v4-outline" onClick={() => setAdding(false)}>Cancel</button></div></div> : null}{person.manualInteractions?.length ? <div className="v4-manual-list">{person.manualInteractions.slice(0, 8).map((item) => <article key={item.id}><Clock3 /><div><strong>{item.title || friendly(item.interactionType)}</strong><small>{fullDate(item.occurredAt)}{item.meaningful ? ' · meaningful by you' : ''}</small>{item.notes ? <p>{item.notes}</p> : null}</div><button aria-label="Delete this offline moment" disabled={busy} onClick={() => remove(item.id)}><Trash2 /></button></article>)}</div> : <p className="v4-caveat">No calls, meetings or in-person moments recorded yet.</p>}</section>
}

export function SymbolicDictionary({ person, onChanged }) {
  const [adding, setAdding] = useState(false)
  const [symbol, setSymbol] = useState('')
  const [meaning, setMeaning] = useState('')
  const [error, setError] = useState('')
  async function save() { setError(''); try { await bridge.people.addSymbolicMeaning(person.id, { symbol, meaning }); setSymbol(''); setMeaning(''); setAdding(false); await onChanged() } catch (err) { setError(errorMessage(err)) } }
  async function remove(id) { await bridge.people.deleteSymbolicMeaning(person.id, id); await onChanged() }
  return <section className="v4-symbols"><div className="v4-section-heading"><div><span>Your meaning</span><h3>Shared shorthand</h3></div><button className="v4-outline" onClick={() => setAdding(!adding)}><MessageCircleMore />Add</button></div><p className="v4-caveat">A 👍, “Reached?” or recurring GIF can mean something different here than anywhere else. Nearness never decides that meaning for you.</p>{error ? <p className="v4-inline-error">{error}</p> : null}{adding ? <div className="v4-inline-form"><label><span>Symbol or phrase</span><input value={symbol} onChange={(event) => setSymbol(event.target.value)} placeholder="👍 or Reached?" /></label><label><span>What it means here</span><textarea value={meaning} onChange={(event) => setMeaning(event.target.value)} placeholder="Received; no more discussion needed." /></label><div><button className="v4-primary" onClick={save}>Save meaning</button><button className="v4-outline" onClick={() => setAdding(false)}>Cancel</button></div></div> : null}{person.symbolicMeanings?.map((item) => <article key={item.id}><b>{item.symbol}</b><p>{item.meaning}</p><button aria-label="Delete this shared meaning" onClick={() => remove(item.id)}><Trash2 /></button></article>)}</section>
}

export function ExperienceProfile({ person, onChanged }) {
  const existing = person.experienceProfile?.snapshot || {}
  const [editing, setEditing] = useState(false)
  const [values, setValues] = useState(() => existing.dimensions || {})
  const [reflection, setReflection] = useState(existing.reflection || '')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { setValues(existing.dimensions || {}); setReflection(existing.reflection || '') }, [person.id, person.experienceProfile?.createdAt])
  const answered = useMemo(() => Object.values(existing.dimensions || {}).filter((value) => value != null).length, [existing])
  async function save() { setBusy(true); setError(''); try { await bridge.people.saveAssessment(person.id, 'relationship_experience_profile', { authority: 'user_report', dimensions: values, reflection, noCompositeScore: true }); setEditing(false); await onChanged() } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  return <section className="v4-experience"><div className="v4-section-heading"><div><span>Your experience</span><h3>A profile, never a score</h3></div><button className="v4-outline" onClick={() => setEditing(!editing)}>{existing.dimensions ? 'Update' : 'Reflect'}</button></div>{error ? <p className="v4-inline-error">{error}</p> : null}{editing ? <div className="v4-experience-form"><p className="v4-caveat">Rate only what feels answerable now. Each dimension stays separate and belongs to your account—not an inference about the other person.</p>{EXPERIENCE_DIMENSIONS.map((dimension) => <label key={dimension}><span>{friendly(dimension)}</span><select value={values[dimension] ?? ''} onChange={(event) => setValues({ ...values, [dimension]: event.target.value === '' ? null : Number(event.target.value) })}><option value="">Unknown / not applicable</option><option value="1">1 · very low</option><option value="2">2 · low</option><option value="3">3 · mixed</option><option value="4">4 · strong</option><option value="5">5 · very strong</option></select></label>)}<label><span>What would you add in your own words?</span><textarea value={reflection} onChange={(event) => setReflection(event.target.value)} /></label><div><button className="v4-primary" disabled={busy} onClick={save}>Save profile</button><button className="v4-outline" onClick={() => setEditing(false)}>Cancel</button></div></div> : existing.dimensions ? <div className="v4-dimension-grid">{EXPERIENCE_DIMENSIONS.filter((dimension) => existing.dimensions[dimension] != null).map((dimension) => <div key={dimension}><span>{friendly(dimension)}</span><strong>{existing.dimensions[dimension]}/5</strong></div>)}{existing.reflection ? <blockquote>{existing.reflection}</blockquote> : null}</div> : <p className="v4-caveat">No self-report yet. Visible messages cannot answer emotional security, mutuality or support fit on their own.</p>}<small>{answered ? `${answered} dimensions answered · user-reported` : 'No composite relationship-quality score'}</small></section>
}
